package com.ptsmods.morecommands.asm;

import com.ptsmods.morecommands.api.Version;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

// Generated by ASMifier
public class EESoundDump extends ASMDump implements Opcodes {

    public static byte[] dump() {
        ClassWriter classWriter = new ClassWriter(0);
        MethodVisitor methodVisitor;

        classWriter.visit(V1_8, ACC_PUBLIC | ACC_SUPER, "com/ptsmods/morecommands/miscellaneous/EESound", null, map("net/minecraft/class_1101", "net/minecraft/client/sound/MovingSoundInstance"), null);

        classWriter.visitSource("EESound.java", null);

        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null);
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(15, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETSTATIC, map("net/minecraft/class_2378", "net/minecraft/util/registry/Registry"), map("field_11156", "SOUND_EVENT"), "L" + map("net/minecraft/class_2378", "net/minecraft/util/registry/Registry") + ";");
            methodVisitor.visitTypeInsn(NEW, map("net/minecraft/class_2960", "net/minecraft/util/Identifier"));
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitLdcInsn("morecommands:ee");
            methodVisitor.visitMethodInsn(INVOKESPECIAL, map("net/minecraft/class_2960", "net/minecraft/util/Identifier"), "<init>", "(Ljava/lang/String;)V", false);;
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, map("net/minecraft/class_2378", "net/minecraft/util/registry/Registry"), map("method_10223", "get"), "(L" + map("net/minecraft/class_2960", "net/minecraft/util/Identifier") + ";)Ljava/lang/Object;", false);;
            methodVisitor.visitTypeInsn(CHECKCAST, map("net/minecraft/class_3414", "net/minecraft/sound/SoundEvent"));
            methodVisitor.visitMethodInsn(INVOKESTATIC, "java/util/Objects", "requireNonNull", "(Ljava/lang/Object;)Ljava/lang/Object;", false);
            methodVisitor.visitTypeInsn(CHECKCAST, map("net/minecraft/class_3414", "net/minecraft/sound/SoundEvent"));
            methodVisitor.visitFieldInsn(GETSTATIC, map("net/minecraft/class_3419", "net/minecraft/sound/SoundCategory"), map("field_15250", "MASTER"), "L" + map("net/minecraft/class_3419", "net/minecraft/sound/SoundCategory") + ";");
            
            if (Version.getCurrent().isNewerThanOrEqual(Version.V1_19)) {
                methodVisitor.visitMethodInsn(INVOKESTATIC, map("net/minecraft/class_5819", "net/minecraft/util/math/random/AbstractRandom"), map("method_43053", "create"), "()L" + map("net/minecraft/class_5819", "net/minecraft/util/math/random/AbstractRandom") + ";", true);
                methodVisitor.visitMethodInsn(INVOKESPECIAL, map("net/minecraft/class_1101", "net/minecraft/client/sound/MovingSoundInstance"), "<init>", "(L" + map("net/minecraft/class_3414", "net/minecraft/sound/SoundEvent") + ";L" + map("net/minecraft/class_3419", "net/minecraft/sound/SoundCategory") + ";L" + map("net/minecraft/class_5819", "net/minecraft/util/math/random/AbstractRandom") + ";)V", false);
            } else
                methodVisitor.visitMethodInsn(INVOKESPECIAL, map("net/minecraft/class_1101", "net/minecraft/client/sound/MovingSoundInstance"), "<init>", "(L" + map("net/minecraft/class_3414", "net/minecraft/sound/SoundEvent") + ";L" + map("net/minecraft/class_3419", "net/minecraft/sound/SoundCategory") + ";)V", false);
            
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(16, label1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(FCONST_0);
            methodVisitor.visitFieldInsn(PUTFIELD, "com/ptsmods/morecommands/miscellaneous/EESound", "pitch", "F");
            Label label2 = new Label();
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(17, label2);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitInsn(ICONST_1);
            methodVisitor.visitFieldInsn(PUTFIELD, "com/ptsmods/morecommands/miscellaneous/EESound", "repeat", "Z");
            Label label3 = new Label();
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(18, label3);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/ptsmods/morecommands/miscellaneous/EESound", "tick", "()V", false);
            Label label4 = new Label();
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(19, label4);
            methodVisitor.visitInsn(RETURN);
            Label label5 = new Label();
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLocalVariable("this", "Lcom/ptsmods/morecommands/miscellaneous/EESound;", null, label0, label5, 0);
            methodVisitor.visitMaxs(5, 1);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "shouldAlwaysPlay", "()Z", null, null);
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(23, label0);
            methodVisitor.visitInsn(ICONST_1);
            methodVisitor.visitInsn(IRETURN);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLocalVariable("this", "Lcom/ptsmods/morecommands/miscellaneous/EESound;", null, label0, label1, 0);
            methodVisitor.visitMaxs(1, 1);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "canPlay", "()Z", null, null);
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(28, label0);
            methodVisitor.visitInsn(ICONST_1);
            methodVisitor.visitInsn(IRETURN);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLocalVariable("this", "Lcom/ptsmods/morecommands/miscellaneous/EESound;", null, label0, label1, 0);
            methodVisitor.visitMaxs(1, 1);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "tick", "()V", null, null);
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(33, label0);
            methodVisitor.visitMethodInsn(INVOKESTATIC, map("net/minecraft/class_310", "net/minecraft/client/MinecraftClient"), map("method_1551", "getInstance"), "()L" + map("net/minecraft/class_310", "net/minecraft/client/MinecraftClient") + ";", false);;
            methodVisitor.visitFieldInsn(GETFIELD, map("net/minecraft/class_310", "net/minecraft/client/MinecraftClient"), map("field_1724", "player"), "L" + map("net/minecraft/class_746", "net/minecraft/client/network/ClientPlayerEntity") + ";");
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, map("net/minecraft/class_746", "net/minecraft/client/network/ClientPlayerEntity"), map("method_19538", "getPos"), "()L" + map("net/minecraft/class_243", "net/minecraft/util/math/Vec3d") + ";", false);;
            methodVisitor.visitVarInsn(ASTORE, 1);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(34, label1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitFieldInsn(GETFIELD, map("net/minecraft/class_243", "net/minecraft/util/math/Vec3d"), map("field_1352", "x"), "D");
            methodVisitor.visitFieldInsn(PUTFIELD, "com/ptsmods/morecommands/miscellaneous/EESound", "x", "D");
            Label label2 = new Label();
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(35, label2);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitFieldInsn(GETFIELD, map("net/minecraft/class_243", "net/minecraft/util/math/Vec3d"), map("field_1351", "y"), "D");
            methodVisitor.visitFieldInsn(PUTFIELD, "com/ptsmods/morecommands/miscellaneous/EESound", "y", "D");
            Label label3 = new Label();
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(36, label3);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitFieldInsn(GETFIELD, map("net/minecraft/class_243", "net/minecraft/util/math/Vec3d"), map("field_1350", "z"), "D");
            methodVisitor.visitFieldInsn(PUTFIELD, "com/ptsmods/morecommands/miscellaneous/EESound", "z", "D");
            Label label4 = new Label();
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(37, label4);
            methodVisitor.visitInsn(RETURN);
            Label label5 = new Label();
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLocalVariable("this", "Lcom/ptsmods/morecommands/miscellaneous/EESound;", null, label0, label5, 0);
            methodVisitor.visitLocalVariable("pos", "L" + map("net/minecraft/class_243", "net/minecraft/util/math/Vec3d") + ";", null, label1, label5, 1);
            methodVisitor.visitMaxs(3, 2);
            methodVisitor.visitEnd();
        }
        classWriter.visitEnd();

        return classWriter.toByteArray();
    }
}
